# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter App Spell Your Name

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: flutter upgrade
      working-directory: ./development
    - run: flutter config --enable-web
      working-directory: ./development
    - run: flutter pub get
      working-directory: ./development
    - run: flutter build web
      working-directory: ./development
    - name: Deploy
      run: |
        cd development/build/web
        git init
        git config user.name  "CI"
        git config user.email "flutter-ci@github.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/g-nxt/spell_your_name.git
        git checkout -b main
        git add .
        git commit -m "Updated app"
        git push --force secure-origin main
